DROP TABLE IF EXISTS users;

CREATE TABLE users (
  uid VARCHAR(10) PRIMARY KEY NOT NULL,
  username VARCHAR(20) NOT NULL,
  register_time DATETIME NOT NULL,
  sex ENUM('男', '女') DEFAULT '男',
  birth DATE DEFAULT NULL,
  location VARCHAR (48) DEFAULT '火星',
  last_login_time DATETIME DEFAULT NULL,
  headimgurl VARCHAR(128),
  status INT DEFAULT 0 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;


DROP TABLE IF EXISTS local_auth;
CREATE TABLE local_auth (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid VARCHAR(10) UNIQUE KEY NOT NULL,
  password VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;